name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
       IMAGE_NAME: springboot-petclinic-actions
       REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
       REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
       #TAGS: v1

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      # exection permission
    - name: adding execution mode 
      run: chmod +x mvnw

    - name: Build with Maven Wrapper
      run: ./mvnw clean install

    - name: ACR login  
      uses: azure/docker-login@v1
      with:
            login-server: pwcinfradockerrg.azurecr.io
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: change to server directory and build
      run: |-
        cd spring-petclinic-server ; 
        mvn clean package docker:build
    
    - name: tagging the image to push to ACR
      run: |-
        docker tag $IMAGE_NAME pwcinfradockerrg.azurecr.io/$IMAGE_NAME:${{ github.sha }}
        
    - name: Push image to ACR
      run: |-
        docker push pwcinfradockerrg.azurecr.io/$IMAGE_NAME:${{ github.sha }}